CREATE TABLE transactions
(
    id         SERIAL PRIMARY KEY,
    amount     NUMERIC(10, 2) NOT NULL,
    type  INTEGER        NOT NULL,
    kind  INTEGER        NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);